# Generated by Django 5.1.1 on 2025-10-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField(help_text='ID único del Pokémon en la PokéAPI', unique=True)),
                ('name', models.CharField(help_text='Nombre del Pokémon', max_length=100)),
                ('types', models.JSONField(help_text="Lista de tipos del Pokémon (ej: ['grass', 'poison'])")),
                ('height', models.IntegerField(help_text='Altura en unidades de la PokéAPI')),
                ('weight', models.IntegerField(help_text='Peso en unidades de la PokéAPI')),
                ('sprite_url', models.URLField(blank=True, help_text='URL de la imagen del Pokémon', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémon',
                'ordering': ['pokemon_id'],
            },
        ),
    ]
