# Generated by Django 5.1.1 on 2025-10-29 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pokedex.pokemon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pokémon Favorito',
                'verbose_name_plural': 'Pokémon Favoritos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'pokemon')},
            },
        ),
    ]
