# Generated by Django 5.1.1 on 2025-10-29 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_userfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pokemon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_favorite', to='pokedex.pokemon')),
            ],
            options={
                'verbose_name': 'Pokémon Favorito',
                'verbose_name_plural': 'Pokémon Favoritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
